[[buildings]]
name = "Giuseppe's Corner Grocery"
story = "In the shadow of the bustling Lower East Side, Giuseppe Rossi, a Sicilian immigrant who arrived in 1905, runs this modest grocery store. Having lost his son in the trenches of France during the Great War, Giuseppe now struggles with post-war shortages, stocking canned goods, bread, and whatever rationed items he can afford. The Armistice on November 11 brings fleeting celebrations, but for Giuseppe, it's a time of quiet grief and mounting debts to suppliers."
occupants = "Giuseppe Rossi (owner, age 52, widowed), occasional part-time helper (young nephew)"
type = "Small commercial shop"
availability = "Open daytime (6 AM - 8 PM)"
x = 200
y = 0
cash = 150

[[buildings]]
name = "The O'Malley Tenement"
story = "This cramped tenement houses the O'Malley family, Irish immigrants who scraped by during the war years. Patrick O'Malley, a dockworker and returning veteran from the 69th Infantry Regiment, came home on November 11 to find his wife Mary and their three children facing eviction due to unpaid rent amid wartime inflation. Patrick drowns his shell shock in cheap whiskey, while Mary takes in laundry to make ends meet. The building buzzes with post-Armistice hope, but underlying tensions from ethnic rivalries simmer—Irish vs. Italian gangs are already forming lines."
occupants = "Patrick O'Malley (age 35, veteran), Mary O'Malley (age 32, homemaker), 3 children (ages 5-12)"
type = "Residential Tenement"
availability = "Accessible anytime, but family more present at night"
x = 200
y = 300
cash = 80

[[buildings]]
name = "Madame Lefevre's Boarding House"
story = "Run by Elise Lefevre, a French war widow who fled Paris after losing her husband at Verdun, this boarding house shelters transient workers and returning soldiers celebrating the Armistice. Elise, sharp-tongued and resourceful, charges steep rates for dingy rooms filled with the smells of cabbage soup and cigarette smoke. On November 11, the house echoes with toasts to peace, but Elise worries about unpaid boarders amid economic uncertainty. Hidden in the basement is a small still for homemade spirits."
occupants = "Elise Lefevre (owner, age 45), 4-6 rotating boarders (mix of veterans and laborers)"
type = "Boarding House"
availability = "Busy evenings (peak interactions); quiet mornings"
x = 200
y = 600
cash = 110

[[buildings]]
name = "Schwartz's Pawn Shop"
story = "Owned by Abraham Schwartz, a Jewish pawnbroker who emigrated from Poland in 1910, this shop is cluttered with war relics—soldiers' watches, medals, and household goods pawned during shortages. Abraham, a shrewd negotiator, survived anti-Semitic tensions and now eyes the Armistice as a boom for redemptions, but fears rising street crime. His daughter Rebecca helps behind the counter, dreaming of Broadway amid the celebrations. The shop's back room holds fenced goods."
occupants = "Abraham Schwartz (age 48), Rebecca Schwartz (age 19, assistant)"
type = "Pawn Shop"
availability = "Open day and night; fortified"
x = 550
y = 0
cash = 750

[[buildings]]
name = "The Vacant Warehouse"
story = "This abandoned warehouse, once a munitions storage during the war, stands empty after the Armistice, its doors boarded up but easily pried. Owned absentee by a shipping company, it's become a haunt for vagrants and petty crooks seeking shelter on cold November nights. Echoes of wartime booms linger in the dusty crates, and rumors of hidden stashes from deserters add allure. On November 11, fireworks from celebrations light the alley, drawing opportunistic scavengers."
occupants = "Occasional vagrants (1-2 random, non-hostile unless provoked)"
type = "Abandoned industrial"
availability = "Always accessible"
x = 550
y = 300
cash = 0

[[buildings]]
name = "Dr. Harlan's Clinic"
story = "Dr. Elias Harlan, a weary physician who treated influenza victims during the 1918 pandemic, operates this small clinic serving the neighborhood's poor. With the Armistice, he's overwhelmed by returning soldiers with wounds and shell shock, charging what he can while dispensing morphine sparingly. His nurse, Clara, harbors secrets of her own—smuggling meds for extra cash. The clinic's sterile facade hides a back office with valuables, and November 11 brings a surge of patients celebrating too hard."
occupants = "Dr. Elias Harlan (age 50), Nurse Clara (age 28), variable patients"
type = "Medical clinic"
availability = "Open daytime; emergency access at night"
x = 550
y = 600
cash = 190